---
title: "Regression and Other Stories"
author: "Shane Kercheval"
output:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
#devtools::install_github('shane-kercheval/rtools')
#library(rtools)
# library(stringr)
# library(ggrepel)
# library(forecast)
#library(scales)
#library(lubridate)

library(knitr)

calculate_plot_width <- function(plot_height) { plot_height * 1.61803398875 }
plot_width_height_5 <- calculate_plot_width(5)
plot_width_height_6 <- calculate_plot_width(6)
plot_width_height_7 <- calculate_plot_width(7)
plot_width_height_8 <- calculate_plot_width(8)
```

```{r downloading_data, eval=FALSE, include=FALSE}
download.file(url='https://raw.githubusercontent.com/avehtari/ROS-Examples/master/ElectionsEconomy/data/hibbs.dat',
              destfile = 'data/hibbs.dat', quiet = TRUE)
```


# Overview

This document includes examples and exercises from `Regression and Other Stories` by Andrew Gelman, Jennifer Hill and Aki Vehtari, 2020, first edition.

# Resources

[Errata](https://avehtari.github.io/ROS-Examples/errata.html)

[Authors' Code](https://avehtari.github.io/ROS-Examples/examples.html#Examples_by_chapters)

# Packages

## Main

```{r message=FALSE, warning=FALSE}
library(rstan)
library(rstanarm)
library(bayesplot)
library(loo)
```

## Additional

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(scales)
```

## Settings

```{r}
theme_set(theme_light())
options(scipen=999) # non-scientific notation
options(dplyr.summarise.inform=F)
```

# Chapter 1

```{r}
hibbs <- read.table('data/hibbs.dat', header = TRUE)
head(hibbs)
```

```{r figure.1.1.a, fig.height=5, fig.width=plot_width_height_5, message=FALSE}
hibbs %>%
    ggplot(aes(x=growth, y=vote)) +
    geom_hline(yintercept = 50, color="red", linetype="dashed") +
    geom_text(aes(label=year)) +
    geom_smooth(method='lm') +
    scale_y_continuous(labels=function(.x)paste0(.x, '%')) +
    labs(title="Forecasting the election from the economy",
         y="Incuming party's vote share",
         x="Average recent growth in personal",
         caption='Figure 1.1')
```

 