---
title: "Regression Examples"
author: "Shane Kercheval"
output:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
#devtools::install_github('shane-kercheval/rtools')
#library(rtools)
library(tidyverse)
# library(scales)
# library(stringr)
# library(lubridate)
# library(ggrepel)
# library(forecast)
library(knitr)

options(scipen=999) # non-scientific notation
options(dplyr.summarise.inform=F)

source('regression_helpers.R')

theme_set(theme_light())

calculate_plot_width <- function(plot_height) { plot_height * 1.61803398875 }
plot_width_height_6 <- calculate_plot_width(6)
plot_width_height_7 <- calculate_plot_width(7)
plot_width_height_8 <- calculate_plot_width(8)
```

# Web spending example

```{r}
## Browsing History. 
## The table has three colums: [machine] id, site [id], [# of] visits
web <- read.csv("data/browser-domains.csv")
## Read in the actual website names and relabel site factor
sitenames <- scan("data/browser-sites.txt", what="character")
web$site <- factor(web$site, levels=1:length(sitenames), labels=sitenames)
## also factor machine id
web$id <- factor(web$id, levels=1:length(unique(web$id)))

head(web)
## get total visits per-machine and % of time on each site
## tapply(a,b,c) does c(a) for every level of factor b.
web %>% count(id, wt=visits) %>% head()

machinetotals <- as.vector(tapply(web$visits, web$id, sum))
machinetotals[1:6]  # same as count above
visitpercent <- 100 * web$visits / machinetotals[web$id]

web %>%
    mutate(visit_percent = visitpercent) %>%
    dplyr::select(-visits)

# dplyr_web <- web %>%
#     mutate(visit_percent = visitpercent) %>%
#     dplyr::select(-visits)
dplyr_web <- web %>%
    add_count(id, wt=visits, name='total_visits') %>%
    mutate(visit_percent = visits / total_visits * 100)
head(dplyr_web)
as.numeric(object.size(dplyr_web)) / 1024^2

# the end result is that each id should add up to 100%
all(dplyr_web %>%
    group_by(id) %>%
    summarise(total_percent = sum(visit_percent)) %>%
    ungroup() %>%
    pull(total_percent) %>% round(9) == 100)

#this is the same thing as the sparse matrix below (only takes up more memory, presumably)
dplyr_web <- dplyr_web %>%
    dplyr::select(-visits, -total_visits) %>%
    pivot_wider(names_from = site,
                values_from = visit_percent)
any(duplicated(dplyr_web$id))
# more than doubles in size
as.numeric(object.size(dplyr_web)) / 1024^2
dplyr_web[1:10, 1:5]

## use this info in a sparse matrix
## this is something you'll be doing a lot; familiarize yourself.
# this seems to auto arrange by web$id
xweb <- sparseMatrix(
	i=as.numeric(web$id),  # i = row = person; this will have duplicates as the same person can appear many times in the dataset (i.e may be assocaited with multiple websites)
	j=as.numeric(web$site),  # j = column = website; this will also have duplicates as each person is associated with many websites and a website with many people
	x=visitpercent,  # x = value at row i column j
	dims=c(nlevels(web$id),  # number of rows
	       nlevels(web$site)),  # number of columns
	dimnames=list(id=levels(web$id),  # row names
	              site=levels(web$site)))  # column names

# smaller than both before/longer dplyr_web
as.numeric(object.size(xweb)) / 1024^2

dplyr_web %>%
    filter(id == 1) %>%
    dplyr::select(`atdmt.com`, `yahoo.com`, `whenu.com`) %>%
    head()
xweb[1, 1:3]
```


```{r}
yspend <- read.csv("data/browser-totalspend.csv", row.names=1)  # us 1st column as row names
yspend <- as.matrix(yspend) ## good practice to move from dataframe to matrix
yspend
```

```{r}
spender <- gamlr(xweb, log(yspend), verb=TRUE)
plot(spender) ## path plot
```

```{r}
head(coef(spender)) ## the coefficients selected under AICc
```


```{r}
head(coef(spender, select=which.min(BIC(spender)))) ## and BIC instead
```

```{r}
cv.spender <- cv.gamlr(xweb, log(yspend), verb=TRUE)
plot(cv.spender)
```

```{r}
plot(cv.spender$gamlr)
```


```{r}
cv.spender$lambda.1se
log(cv.spender$lambda.1se)
head(coef(cv.spender)) ## 1se rule; see ?cv.gamlr
```

```{r}
cv.spender$lambda.min
log(cv.spender$lambda.min)
head(coef(cv.spender, select="min")) ## min cv selection
```


```{r}
fitted(cv.spender)
predict(cv.spender, select="min")
```


# Hockey Example

```{r data}
library(gamlr) # loads Matrix as well
#help(hockey) # describes the hockey data and shows an example regression
# each record corresponds to every goal scored, with a binary for home/away team
data(hockey) # load the data
head(goal)
head(player)
# player, team, goal hae the same number of rows
dim(player)
nrow(goal)
dim(team)
```

